CREATE TABLE USUARIO (
	id_usuario NUMBER(9) PRIMARY KEY,
	cpf CHAR(11) UNIQUE NOT NULL,
	email VARCHAR2(300) NOT NULL UNIQUE,
	nome VARCHAR2(255) NOT NULL,
	senha VARCHAR2(300) NOT NULL,
	tipo NUMBER(1) NOT NULL,
	endereco varchar2(600) NOT NULL,
	contatos varchar2(100) NOT NULL
);

CREATE TABLE ADMINISTRATIVO (
	id_administrativo NUMBER(9) PRIMARY KEY,
	id_usuario NUMBER(9) NOT NULL UNIQUE,
	CONSTRAINT FK_ADMINISTRATIVO_USUARIO FOREIGN KEY (id_usuario) REFERENCES Usuario (id_usuario)
);

CREATE TABLE CONVENIO (
	id_convenio NUMBER(9) PRIMARY KEY,
	cadastro_orgao_regulador VARCHAR2(40) NOT NULL,
	taxa_abatimento DECIMAL(4,2) NOT NULL
);

CREATE TABLE CLIENTE (
	id_cliente NUMBER(9) PRIMARY KEY,	
	id_convenio NUMBER(9),	
	id_usuario NUMBER(9) NOT NULL UNIQUE,
	CONSTRAINT FK_CLIENTE_USUARIO FOREIGN KEY (id_usuario) REFERENCES Usuario (id_usuario),
	CONSTRAINT FK_CLIENTE_CONVENIO FOREIGN KEY (id_convenio) REFERENCES Convenio (id_convenio)
);

CREATE TABLE ESPECIALIDADE (
	id_especialidade NUMBER(9) PRIMARY KEY,
	valor DECIMAL(10,2) NOT NULL,
	nome VARCHAR2(60) NOT NULL
);


CREATE TABLE MEDICO (
	id_medico NUMBER(9) PRIMARY KEY,
	crm CHAR(13) UNIQUE NOT NULL,
	id_especialidade NUMBER(9) NOT NULL,
	id_usuario NUMBER(9) NOT NULL UNIQUE,
	CONSTRAINT FK_MEDICO_USUARIO FOREIGN KEY (id_usuario) REFERENCES Usuario (id_usuario),
	CONSTRAINT FK_MEDICO_ESPECIALIDADE FOREIGN KEY (id_especialidade) REFERENCES Especialidade (id_especialidade)
);


CREATE TABLE AGENDAMENTO (
	id_agendamento NUMBER(9) PRIMARY KEY,	
	id_cliente NUMBER(9) NOT NULL,
	id_medico NUMBER(9) NOT NULL,
	tratamento VARCHAR2(40),
	exame VARCHAR2(40),
	data_horario DATE NOT NULL,
	CONSTRAINT FK_AGENDAMENTO_MEDICO FOREIGN KEY (id_medico) REFERENCES MEDICO (id_medico),
	CONSTRAINT FK_AGENDAMENTO_CLIENTE FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id_cliente)
);

CREATE SEQUENCE seq_endereco
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;

CREATE SEQUENCE seq_contato
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;

CREATE SEQUENCE seq_usuario
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;

CREATE SEQUENCE seq_cliente
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;

CREATE SEQUENCE seq_medico
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;

CREATE SEQUENCE seq_administrativo
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;

CREATE SEQUENCE seq_agendamento
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;

CREATE SEQUENCE seq_convenio
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;

CREATE SEQUENCE seq_especialidade
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;




ALTER TABLE USUARIO ADD cep char(8);
ALTER TABLE USUARIO modify cep NOT NULL;
ALTER TABLE USUARIO ADD numero number(9);
ALTER TABLE USUARIO modify numero NOT null;
